name: Bug report
description: Report a reproducible defect in TheWorkshop
labels: ["type:bug", "status:needs-repro"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Reproducible reports get triaged fastest.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What failed?
      placeholder: Short problem statement
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Provide exact commands/inputs to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Logs / Artifacts
      description: Relevant file paths, snippets, screenshots, or command output.
  - type: input
    id: version
    attributes:
      label: Version / Commit
      placeholder: main@<sha> or v0.1.0
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched for existing issues
          required: true
        - label: I can reproduce this consistently
          required: true
