name: Feature request
description: Propose an enhancement with clear acceptance criteria
labels: ["type:enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Opportunity
      description: What user outcome is missing today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Change
      description: Describe expected behavior and rough implementation idea.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Objective checks that determine done.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues/discussions
          required: true
